
spring.application.name=Ripple

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/Ripple}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Murtaza@786}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true

# Server
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never